### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by J0ET0M**
removed +0 from UTC because this could lead to daylight saving settings

### CODE REVIEW

**Comment by N-010** [comment]
What do I use if I want UTC0?

**Comment by J0ET0M** [comment]
not sure if i understand you right. just UTC without any +/- because normally +/- refer to a daylight saving time. at the end it is just important the the computer does not daylight savings. which timezone you select (if you can select) does not matter. just the time has to be UTC.

**Comment by N-010** [comment]
Is it right, then, to write like this?
Set time to UTC TIME 0 (do not use +/- (UTC +0) as your computer should not respect daylight savings)

**Review by N-010 — CHANGES_REQUESTED** [review]
Can you add `0` to your change?
It's not clear which UTC should be set
Example:
Set time to UTC TIME `0` (do not use +/- (UTC +0) as your computer should not respect daylight savings)

**Pull request merged**
